version: '3.8'

services:
  db-mysql:
    image: mysql:latest
    container_name: db-mysql
    ports:
      - "3306:3306"
    networks:
      - some-network
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}
    volumes:
      - data-mysql:/var/lib/mysql

  db-mongodb:
    image: mongo:latest
    container_name: db-mongodb
    ports:
      - "27017:27017"
    networks:
      - some-network
    volumes:
      - data-mongodb:/data/db

  api-data:
    build:
      context: ./data
      dockerfile: Dockerfile
    container_name: api-express-data
    ports:
      - "8080:8080"
    networks:
      - some-network
    environment:
      - PORT=8080
      - MONGODB_URL=${URL_MONGODB}
      - URL_BASE=${URL_WEB}
      - MYSQL_HOST=db-mysql
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USERNAME=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
    depends_on:
      - db-mongodb
      - db-mysql

  api-websocket:
    build: 
      context: ./websocket
      dockerfile: Dockerfile
    container_name: api-express-websocket
    ports:
      - "8040:8040"
    networks:
      - some-network
    environment:
      - URL_BASE=${URL_WEB}
      - PORT=8040

  api-auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    container_name: api-django-auth
    ports:
      - "8000:8000"
    networks:
      - some-network
    environment:
      - DATABASE_HOST=db-mysql
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - URL_BASE=${URL_WEB}
    depends_on:
      - db-mysql
      - db-mongodb
      - api-data
      - api-websocket
      - api-mqtt      

  api-mqtt:
    build: 
      context: ./mqtt
      dockerfile: Dockerfile
    container_name: api-express-mqtt
    ports:
      - "8060:8060"

    networks:

      - some-network
    environment:
      - URL_BASE=${URL_WEB}
      - PORT=8060
      - MONGODB_URL=${URL_MONGODB}
      - MQTT_CLIENT_ID=${MQTT_CLIENT_ID}
      - MQTT_USERNAME=${MQTT_USERNAME}
      - MQTT_PWD=${MQTT_PWD}
      - MQTT_URL=${MQTT_URL}
    depends_on:
      - db-mongodb


networks:
  some-network:
    driver: bridge


volumes:
  data-mongodb:
  data-mysql: