version: '3.8'

services:
  db-mysql:
    image: mysql:latest
    container_name: db-mysql
    ports:
      - "3306:3306"
    networks:
      - some-network
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=tecsup
    volumes:
      - data-mysql:/var/lib/mysql

  db-mongodb:
    image: mongo:latest
    container_name: db-mongodb
    ports:
      - "27017:27017"
    networks:
      - some-network
    volumes:
      - data-mongodb:/data/db

  api-data:
    build:
      context: ./data
      dockerfile: Dockerfile
    container_name: api-express-data
    ports:
      - "8080:8080"
    networks:
      - some-network
    environment:
      - MONGODB_URL=mongodb://db-mongodb:27017/tecsup
      - URL_BASE=http://localhost:4200
      - PORT=8080
      - MYSQL_HOST=db-mysql
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=tecsup
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=admin
    depends_on:
      - db-mongodb
      - db-mysql

  api-websocket:
    build: 
      context: ./websocket
      dockerfile: Dockerfile
    container_name: api-express-websocket
    ports:
      - "8040:8040"
    networks:
      - some-network
    environment:
      - URL_BASE=http://localhost:4200
      - PORT=8040

  api-auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    container_name: api-django-auth
    environment:
      - DATABASE_HOST=db-mysql
      - DATABASE_NAME=tecsup
      - DATABASE_USER=root
      - DATABASE_PASSWORD=admin
    ports:
      - "8000:8000"
    networks:
      - some-network
    depends_on:
      - db-mysql
      - db-mongodb
      - api-data
      - api-websocket

networks:
  some-network:
    driver: bridge

volumes:
  data-mongodb:
  data-mysql: